version "4.10"

#include "zscript/undeadzeratul/elements/UZAmmoCounters.zs"
#include "zscript/undeadzeratul/elements/UZArmour.zs"
#include "zscript/undeadzeratul/elements/UZBackground.zs"
#include "zscript/undeadzeratul/elements/UZCompass.zs"
#include "zscript/undeadzeratul/elements/UZEKG.zs"
#include "zscript/undeadzeratul/elements/UZEncumbrance.zs"
#include "zscript/undeadzeratul/elements/UZFullInventory.zs"
#include "zscript/undeadzeratul/elements/UZHeartbeat.zs"
#include "zscript/undeadzeratul/elements/UZInventory.zs"
#include "zscript/undeadzeratul/elements/UZItemAdditions.zs"
#include "zscript/undeadzeratul/elements/UZKeys.zs"
#include "zscript/undeadzeratul/elements/UZMugshot.zs"
#include "zscript/undeadzeratul/elements/UZPosition.zs"
#include "zscript/undeadzeratul/elements/UZStimCounter.zs"
#include "zscript/undeadzeratul/elements/UZWeaponSprite.zs"
#include "zscript/undeadzeratul/elements/UZWeaponStash.zs"
// #include "zscript/undeadzeratul/elements/UZWeaponStatus.zs"
#include "zscript/undeadzeratul/elements/UZWoundCounter.zs"