version "4.10"

#include "zscript/UZAmmoCounters.zs"
#include "zscript/UZCompass.zs"
#include "zscript/UZEKG.zs"
#include "zscript/UZEncumbrance.zs"
#include "zscript/UZFullInventory.zs"
#include "zscript/UZHeartbeat.zs"
#include "zscript/UZInventory.zs"
#include "zscript/UZKeys.zs"
#include "zscript/UZMugshot.zs"
#include "zscript/UZOverlay.zs"
#include "zscript/UZPosition.zs"
#include "zscript/UZWeaponSprite.zs"
// #include "zscript/UZWeaponStatus.zs"
#include "zscript/UZWoundCounter.zs"