name: Build PK3
description: Builds the PK3
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: montudor/action-zip@v1
    with:
      args: zip -r "hideous-helmet-extended-${{ env.SUFFIX }}.pk3" . -i graphics/* zscript/* CHANGELOG.md CVARINFO KEYCONF LANGUAGE.* LICENSE MAPINFO MENUDEF readme.md TEXTURES.* zscript.zs
