name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/build-pk3
      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./*.pk3
