name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: build-suffix
        shell: bash
        run: echo "SUFFIX=${{ github.ref_name }}-$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"
      - uses: ./.github/workflows/build-pk3
        env:
          SUFFIX: ${{ steps.build-suffix.outputs.SUFFIX }}
      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./*.pk3
